kind: Cluster
name: cilium-testing
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  ipFamily: dual
  podSubnet: 10.244.0.0/16,fd00:10:244::/56
  serviceSubnet: 10.96.0.0/16,fd00:10:96::/112
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 2345
        hostPort: 23401
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 2346
        hostPort: 23501
        listenAddress: 127.0.0.1
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 2345
        hostPort: 23411
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 2346
        hostPort: 23511
        listenAddress: 127.0.0.1
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 2345
        hostPort: 23412
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 2346
        hostPort: 23512
        listenAddress: 127.0.0.1
        protocol: TCP
