kind: Cluster
name: cilium-testing
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  ipFamily: dual
  podSubnet: "10.1.0.0/16,c::/63"
  serviceSubnet: "10.2.0.0/16,d::/108"
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
nodes:
- role: control-plane
