apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cilium-testing
  region: eu-north-1
  version: "1.29"
  tags:
    usage: dev-cilium-testing
    owner: smagnani96
vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: false
managedNodeGroups:
  - name: cilium-testing
    desiredCapacity: 2
    taints:
      - key: "node.cilium.io/agent-not-ready"
        value: "true"
        effect: "NoExecute"
