debug:
  enabled: true
  verbose: datapath
bpf:
  monitorAggregation: none
  # ---------------- Routing
  # masquerade: false
image:
  repository: quay.io/cilium/cilium-dev
  tag: local
  pullPolicy: IfNotPresent
  useDigest: false
operator:
  enabled: true
  # ---------------- Observability
  #prometheus:
  #  enabled: true
  replicas: 1
  image:
    override: ~
    repository: quay.io/cilium/operator
    tag: local
    useDigest: false
    pullPolicy: IfNotPresent
    suffix: ""
ipam:
  mode: kubernetes
#ipv4PodSubnets:
#  - 192.168.0.0/16
envoy:
  enabled: false
ipv4:
  enabled: true
ipv6:
  enabled: true
# -------------- KPR
# kubeProxyReplacement: "true"
#k8sServiceHost: 127.0.0.1
#k8sServicePort: 6443
#kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256,[::]:10256"
# --------------- Encryption
encryption:
  enabled: true
  nodeEncryption: false
  encryptedOverlay: false
  type: ipsec
# --------------- Routing
#routingMode: native
#ipv4NativeRoutingCIDR: 10.244.0.0/16
#ipv6NativeRoutingCIDR: fd00:10:244::/56
#autoDirectNodeRoutes: true
#endpointRoutes:
#  enabled: true
#enableIPv4Masquerade: false
#enableIPv6Masquerade: false
#enableMasqueradeRouteSource: false
# ------------- Observability
#prometheus:
#  enabled: true
#hubble:
#  enabled: true
#  metrics:
#    enableOpenMetrics: true
#    enabled:
#      [
#        dns,
#        drop,
#        tcp,
#        flow,
#        port-distribution,
#        icmp,
#        httpV2:exemplars=true;labelsContext=source_ip,
#        source_namespace,
#        source_workload,
#        destination_ip,
#        destination_namespace,
#        destination_workload,
#        traffic_direction,
#      ]
