apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: migrate-svc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrate-svc-client
  template:
    metadata:
      labels:
        app: migrate-svc-client
        zgroup: migrate-svc
    spec:
      containers:
        - name: server
          image: docker.io/cilium/migrate-svc-test:v0.0.2
          imagePullPolicy: IfNotPresent
          command: ["/client", "migrate-svc.default.svc.cluster.local.:8000"]
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: migrate-svc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrate-svc-server
  template:
    metadata:
      labels:
        app: migrate-svc-server
        zgroup: migrate-svc
    spec:
      containers:
        - name: server
          image: docker.io/cilium/migrate-svc-test:v0.0.2
          imagePullPolicy: IfNotPresent
          command: ["/server", "8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: migrate-svc
spec:
  ports:
    - port: 8000
  selector:
    app: migrate-svc-server
